image: ubuntu:latest

google-tests:
  stage: test  
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - apt-get -y update && apt-get -y dist-upgrade
    - apt-get -y install gcc g++ cmake autoconf git nlohmann-json3-dev curl libcurl4-openssl-dev
  script:
    - mkdir crawler_build
    - cd crawler_build
    - cmake ../tests
    - cmake --build .
    - ./crawler_tests --gtest_output="xml:report.xml"


linting:
  stage: test  
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script: 
    - apt-get -y update && apt-get -y dist-upgrade
    - apt-get -y install gcc g++ cmake autoconf
    - apt-get -y install clang clang-tidy clang-format nlohmann-json3-dev curl libcurl4-openssl-dev
  script:
    - cd libSearchSECOCrawler
    - clang-tidy *.cpp -- -I../external/curlcpp/include/ -std=c++20
    - clang *.cpp -I../external/curlcpp/include/ -fsyntax-only -std=c++20

