image: ubuntu:latest

google-tests:
  stage: test  
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - apt-get -y update && apt-get -y dist-upgrade
    - apt-get -y install gcc g++ cmake autoconf git nlohmann-json3-dev curl
  script:
    - mkdir crawler_build
    - cd crawler_build
    - cmake ../Crawler-Test
    - cmake --build .
    - ./crawler_tests --gtest_output="xml:report.xml"


linting:
  stage: test  
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script: 
    - apt-get -y update && apt-get -y dist-upgrade
    - apt-get -y install gcc g++ cmake autoconf
    - apt-get -y install clang clang-tidy clang-format nlohmann-json3-dev curl
  script:
    - cd Crawler
    - clang-tidy *.cpp -- -I../curlcpp/include/
    - clang *.cpp -I../curlcpp/include/ -fsyntax-only

