image: gcc

google-tests:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake autoconf nlohmann-json3-dev curl
  script:
    - mkdir crawler_build
    - cd crawler_build
    - cmake ../Crawler-Test
    - cmake --build .
    - ./crawler_tests --gtest_output="xml:report.xml"


linting:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake autoconf
    - apt-get -y install clang clang-tidy clang-format nlohmann-json3-dev curl
  script:
    - cd Crawler
    - clang-tidy *.cpp --
    - clang *.cpp -fsyntax-only

