name: Testing pipeline
on: [push, pull_request]
jobs:

  Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
             sudo apt-get -qq update
             sudo apt-get -y -qq dist-upgrade
             sudo apt-get -y -qq install gcc g++ cmake autoconf git nlohmann-json3-dev curl libcurl4-openssl-dev
      - name: Tests
        run: |
             mkdir crawler_build
             cd crawler_build
             cmake ../tests
             cmake --build .
             ./crawler_tests --gtest_output="xml:report.xml"
             
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
             sudo apt-get -qq update
             sudo apt-get -y -qq dist-upgrade
             sudo apt-get -y -qq install gcc g++ cmake autoconf clang clang-tidy clang-format nlohmann-json3-dev curl libcurl4-openssl-dev
      - name: Run linting
        run: |
             cd libSearchSECOCrawler
             clang-tidy *.cpp -- -I../external/curlcpp/include/ -std=c++20
             clang *.cpp -I../external/curlcpp/include/ -fsyntax-only -std=c++20